### ISSUE TITLE
Баг в актуальном коде (9 задание) с вызовом функции ```snprintf```

### ISSUE THREAD

**Issue by IAmFunkyFrog** [AntonKozlov/os226-2021#121]
По какой-то на данный момент не выясненной причине функция ```snprintf``` вот в этом месте не работает:
https://github.com/AntonKozlov/os226-2021/blob/9c3f8ed2cf6983881c2d16bb5007e366ebaf42d3/sched.c#L403
Проверено, что если данную строку убрать, то все работает, как надо: #120.

**Comment by IAmFunkyFrog** [comment]
Кажется, что конкретно в моем случае (возможно и в остальных тоже) проблема в том, что ассемблерная инструкция ```movaps %xmm0,(%rsp)``` ожидает, что адрес в %rsp будет выровнен по 16 байтам, однако видимо в моем случае 
<pre>
(gdb) x/x $rsp
0x5581fd2a5fd8 <taskarray+7800>:	0xfd2a6138
</pre>
адрес не выровнен.
Подумал так посмотрев данный [ответ](https://stackoverflow.com/questions/67243284/why-movaps-causes-segmentation-fault) на стековерфлоу.

**Comment by AntonKozlov** [comment]
о, это отличное наблюдение. Это скорее всего требование из ABI (было бы неплохо найти ссылку), а мы его нарушаем, когда задаём стек. Но только `printf` закладывается на это требование. Но нам всё равно надо выровнять стек, чтобы соответствовать ABI
